### ISSUE TITLE
Feature Request: Allow us to see if accepting a contract will make another contract unavailable before accepting the contract

### ISSUE THREAD

**Issue by Clayell** [KSP-RO/ContractConfigurator#10]
Currently, the only way to see if a contract will make another contract unavailable is by either not having the contract available to even accept or by accepting the contract.

[Unavailable contract showing what contracts cannot be accepted at the same time](https://cdn.discordapp.com/attachments/617156220146417664/1089662937477693481/image.png)

[Available contract that does not show what contracts cannot be accepted at the same time, if any](https://cdn.discordapp.com/attachments/617156220146417664/1089663277723832381/image.png)

**Comment by siimav** [comment]
I imagine the easiest *fix* for this is to manually update the contract description text with the details about inter-contract dependencies.

**Comment by Clayell** [comment]
Manually as in go into the file myself and write it in? That seems like a long workaround that could pretty easily be fixed. The information about this stuff is already known, it just needs to be put in there by the mod.

**Comment by Clayell** [comment]
Any updates?

**Comment by siimav** [comment]
https://github.com/KSP-RO/ContractConfigurator/commit/024354874abc6dd345d2462bce91ad66c12967b3
There's a warning now when trying to accept a conflicting contract.

**Comment by Clayell** [comment]
> [0243548](https://github.com/KSP-RO/ContractConfigurator/commit/024354874abc6dd345d2462bce91ad66c12967b3)
> There's a warning now when trying to accept a conflicting contract.

Nice, thanks!
