### ISSUE TITLE
Possible memory leak caused by TitleTracker.cs

### ISSUE THREAD

**Issue by Calvin-13** [KSP-RO/ContractConfigurator#8]
KSPCF's logging feature tells me that this mod has a possible GameEvents leak issue, and I have had multiple crashes caused by memory access violations in a heavily modded career using Contract Configurator. I am unsure exactly what is going on but figured I should report it.

[LOG 20:39:49.744] [KSPCF:MemoryLeaks] Potential GameEvents leaks for scene Flight :
- "onVesselRenamed" had 1633 subscribers on last scene switch, now it has 1977. Those subscribers are likely leaking :
  - ContractConfigurator:TitleTracker - Subscriptions : 1632/1976 (last/now)
- "Contract.ParameterChange" had 1632 subscribers on last scene switch, now it has 1976. Those subscribers are likely leaking :
  - ContractConfigurator:TitleTracker - Subscriptions : 1632/1976 (last/now)

Also noticed:
- "OnContractLoaded" had 247 subscribers on last scene switch, now it has 299. Those subscribers are likely leaking :
  - ContractConfigurator:VesselParameterGroup - Subscriptions : 247/299 (last/now)

**Comment by Calvin-13** [comment]
I am using version 2.2.2, installed via CKAN.

**Comment by siimav** [comment]
Checked my own log after a short _play_ session and I'm not noticing any of those leaks. Can anyone else confirm that they're getting those as well?

**Comment by Calvin-13** [comment]
Could it be possible that the issue is caused by a specific contract pack?

Currently, I have:
- Bases & Stations Reborn
- Clever Sats
- Exploration Plus
- Giving Aircraft a Purpose
- Kerbin Side Remastered GAP and its addons
- Research Advancement Division
- Tourism Plus

**Comment by siimav** [comment]
It's certainly possible that that contracts in any of those packs use attributes that weren't used/active in my own install.
